### ISSUE TITLE
Puede ser que las instrucciones 8xy6 y 8xyE esten incorrectas.

### ISSUE THREAD

**Issue by luischavez** [danirod/chip8#1]
Segun esta pagina [http://mattmik.com/chip8.html] lo correcto seria:

8XY6 - Store the value of register VY shifted right one bit in register VX
Set register VF to the least significant bit prior to the shift.

8XYE - Store the value of register VY shifted left one bit in register VX
Set register VF to the most significant bit prior to the shift.

**Comment by danirod** [comment]
Hm, según estas tres páginas SHR y SHL sólo trabajan con VX, no con VY.
- http://devernay.free.fr/hacks/chip8/C8TECH10.HTM#8xy6
- http://es.wikipedia.org/wiki/CHIP-8#Tabla_de_instrucciones
- http://chip8.sourceforge.net/chip8-1.1.pdf

Es un poco sospechoso que el código de la instrucción acepte una Y (8XY6 y 8XYE), pero parece que no se trabaja con la Y para nada.

**Comment by danirod** [comment]
Por cerrar el issue, he encontrado en documentación más seria que inicialmente SHR y SHL sí trabajaban con Vy. Sin embargo las implementaciones actuales únicamente trabajan con Vx. Desconozco si esto puede traer problemas de compatibilidad con ROMs que utilicen el antiguo sistema, pero en cualquier caso el emulador es únicamente compatible con las implementaciones actuales.
