### ISSUE TITLE
CPU consume is too high

### ISSUE THREAD

**Issue by danirod** [danirod/chip8#26]
CHIP-8 eats way too much CPU on the host machine.

Run the emulator on any operating system and check the CPU usage. It will go up to 90%-100% and stay until emulator gets closed. This is a problem on less powerful computers and it can drain batteries on laptops.

**Comment by Guerra24** [comment]
Here is a fixed update game loop. It handles a fixed update for every second, this allows to always run at the same speed independently of the fps also sleeps the thread in case of the updates were completed. [Code](https://gist.github.com/Guerra24/adda4e4e214abf68b4caf7e8890105cd). Extracted from java code, some parts needs a port to C.
